name: code_gen
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.0.0
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.0.2
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  go_router_builder: ^1.1.7
  riverpod_generator: ^2.1.4
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
